### ISSUE TITLE
cargo test failure

### ISSUE THREAD

**Issue by ninegua** [dfinity/candid#424]
With current master (55d34ec060bd9dc735ed577e6924ddac79a415bf)

```
cargo test
...
test test_vector ... ok
test test_struct ... ok
test test_error ... FAILED
test test_variant ... ok

failures:

---- test_error stdout ----
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(Cannot parse header 444944

Caused by:
    binary parser error: io error)', rust/candid/tests/serde.rs:721:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(Cannot parse header 4449444c

Caused by:
    binary parser error: len at byte offset 4)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(No more values on the wire, the expected type int32 is not opt or reserved)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(Cannot parse header 4449444c017c

Caused by:
    binary parser error: -4 is not a valid future type at byte offset 5)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(Cannot parse header 4449444c026e0100

Caused by:
    binary parser error: 0 is not a valid future type at byte offset 7)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(Trailing value after finishing deserialization

Caused by:
    input: 4449444c00017e01_01
    wire_type: bool, expect_type: bool)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(Fail to decode argument 0 from bool to bool

Caused by:
    0: input: 4449444c00017e_
       wire_type: bool, expect_type: bool
    1: binary parser error: io error)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(Cannot parse header 4449444c00010001

Caused by:
    0: Invalid argument entry 0: IndexType { index: 0 }
    1: type index 0 out of range)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(Fail to decode argument 0 from table1 to reserved

Caused by:
    0: input: 4449444c026c010a016d0001012020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020_
       table: type table0 = record { 10 : table1 }
       type table1 = vec table0
       wire_type: vec table0, expect_type: vec table0
    1: binary parser error: self_0 at byte offset 465)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'assertion failed: `(left == right)`
  left: `Some(false)`,
 right: `Some(true)`', rust/candid/tests/serde.rs:736:5


failures:
    test_error

test result: FAILED. 25 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p candid --test serde`
```

I wonder how did it pass CI?

**Comment by ninegua** [comment]
We can compare these two error messages:

Failed case (copied from above)
```
Caused by:
    0: input: 4449444c026c010a016d0001012020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020_
       table: type table0 = record { 10 : table1 }
       type table1 = vec table0
       wire_type: vec table0, expect_type: vec table0
    1: binary parser error: self_0 at byte offset 465)', rust/candid/tests/serde.rs:721:46
thread 'test_error' panicked at 'assertion failed: `(left == right)`
  left: `Some(false)`,
 right: `Some(true)`', rust/candid/tests/serde.rs:736:5
 ```
 
 Success case (copied from a success run with --show-output)
```
 Caused by:
    0: input: 4449444c026c010a016d000101202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020_2020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202020
       table: type table0 = record { 10 : table1 }
       type table1 = vec table0
       wire_type: record { 10 : table1 }, expect_type: record { 10 : table1 }
    1: Recursion limit exceeded at depth 714)', rust/candid/tests/serde.rs:721:46
```

It was evident that "Recursion limit" wasn't triggered in the failed run. So [this test case](https://github.com/dfinity/candid/blob/master/rust/candid/tests/serde.rs#L30-L35) seems not deterministic, i.e., it relies on runtime behavior and Rust compiler internals.
```
    check_error(
        || {
            test_decode(b"DIDL\x02\x6c\x01\x0a\x01\x6d\x00\x01\x01

                                                                                                                                                                      ", &candid::Reserved)
        },
        "Recursion limit exceeded",
    );
```

**Comment by chenyan-dfinity** [comment]
I see. It should fail with the default Rust stack size, which is what the CI is configed. If you run the test with a larger stack size, it won't trigger the recursion limit. It would fail at the end as you see in the failed case.
